import { db } from "@/src/db";
import { 
  invoices, 
  receiptUploads, 
  verificationAttempts, 
  auditLogs, 
  notifications 
} from "@/src/db/schema";
import { eq, and, sql } from "drizzle-orm";
import { google, createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText } from "ai";
import { createHash } from "crypto";
import { type GeminiOcrResult, type VerificationScore } from "@/src/types/verification";
import { NotificationService } from "./notifications";

export class VerificationEngine {
  /**
   * Run OCR receipt details extraction using Gemini Vision
   */
  static async extractReceiptDetails(
    base64Data: string,
    mimeType: string
  ): Promise<GeminiOcrResult & { suspected_fraud: boolean; fraud_reasons: string[] }> {
    const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY || process.env.GEMINI_API_KEY;
    
    if (!apiKey) {
      console.warn("[VerificationEngine] GEMINI_API_KEY is not defined. Falling back to mock OCR extraction.");
      return this.getMockOcrResult();
    }

    const prompt = `You are a strict payment verification auditor. Analyze the uploaded document and extract details to verify if it is a genuine bank transfer receipt/proof of payment.
    
    Extract the following details from the receipt:
    1. Amount: The final success transfer amount (as a number).
    2. Account Number: The destination bank account number the money was sent to.
    3. Account Name: The destination bank account name the money was sent to.
    4. Bank Name: The destination bank name (e.g. OPay, GTBank, Zenith, Access, Kuda, Moniepoint, etc.).
    5. Transaction Reference: The session ID, transaction reference number, or payment reference ID.
    6. Sender Name: The name of the client/sender.
    7. Transaction Date: The date of the transaction in YYYY-MM-DD format.
    8. Confidence Score: A confidence score (0 to 100) of your extraction quality.
    
    Additionally, perform these security and fraud checks:
    - Look for indicators of screenshot tampering or font editing (e.g. inconsistent font size, alignment issues, digital paint coverups).
    - Determine if this is a fake PDF/receipt generated by a payment template instead of a real bank transaction success screen.
    - Set "suspected_fraud" to true if you detect suspicious artifacts, font mismatched characters, or standard receipt generator markers.
    
    Return ONLY a JSON object with this exact structure (do not include markdown backticks or extra text, just raw JSON):
    {
      "amount": 12500,
      "account_number": "1234567890",
      "account_name": "John Doe",
      "bank_name": "Zenith Bank",
      "transaction_reference": "TXN987654321",
      "sender_name": "Jane Smith",
      "transaction_date": "2026-06-10",
      "confidence_score": 95,
      "suspected_fraud": false,
      "fraud_reasons": []
    }`;

    try {
        const googleInstance = createGoogleGenerativeAI({ apiKey });
        const { text } = await generateText({
          model: googleInstance("gemini-2.5-flash"),
          messages: [
            {
              role: "user",
              content: [
                { type: "text", text: prompt },
                { type: "file", data: base64Data, mediaType: mimeType }
              ]
            }
          ]
        });

      const cleanedText = text.replace(/```json/gi, "").replace(/```/g, "").trim();
      const parsed = JSON.parse(cleanedText);
      return {
        amount: Number(parsed.amount || 0),
        account_number: String(parsed.account_number || "").trim(),
        account_name: String(parsed.account_name || "").trim(),
        bank_name: String(parsed.bank_name || "").trim(),
        transaction_reference: String(parsed.transaction_reference || "").trim(),
        sender_name: String(parsed.sender_name || "").trim(),
        transaction_date: String(parsed.transaction_date || "").trim(),
        confidence_score: Number(parsed.confidence_score || 0),
        suspected_fraud: !!parsed.suspected_fraud,
        fraud_reasons: Array.isArray(parsed.fraud_reasons) ? parsed.fraud_reasons : []
      };
    } catch (err) {
      console.error("[VerificationEngine] Gemini Vision call failed:", err);
      // Fallback to mock in case API is failing/unreachable
      return this.getMockOcrResult();
    }
  }

  /**
   * Run the weighted scoring matching logic against the actual invoice.
   */
  static async scoreReceipt(
    ocr: GeminiOcrResult & { suspected_fraud: boolean; fraud_reasons: string[] },
    invoice: { amount: number; bankName?: string | null; accountName?: string | null; accountNumber?: string | null; createdAt: Date },
    submittedRef: string
  ): Promise<VerificationScore> {
    let amountScore = 0;
    let accountNumberScore = 0;
    let accountNameScore = 0;
    let dateScore = 0;
    let referenceScore = 0;
    const fraudFlags: string[] = [];

    // 1. Amount Match (40 points)
    // Allow small decimal differences but must be exact matching values
    const diff = Math.abs(ocr.amount - invoice.amount);
    if (diff < 1.0) {
      amountScore = 40;
    } else {
      fraudFlags.push("AMOUNT_MISMATCH");
    }

    // 2. Account Number Match (25 points)
    const normalizedExtractedAcc = ocr.account_number.replace(/\D/g, "");
    const normalizedInvoiceAcc = (invoice.accountNumber || "").replace(/\D/g, "");
    if (normalizedInvoiceAcc && normalizedExtractedAcc.includes(normalizedInvoiceAcc)) {
      accountNumberScore = 25;
    } else {
      fraudFlags.push("ACCOUNT_NUMBER_MISMATCH");
    }

    // 3. Account Name Match (15 points)
    const extNameUpper = ocr.account_name.toUpperCase();
    const invNameUpper = (invoice.accountName || "").toUpperCase();
    if (invNameUpper && (extNameUpper.includes(invNameUpper) || invNameUpper.includes(extNameUpper) || this.computeJaroWinkler(extNameUpper, invNameUpper) > 0.8)) {
      accountNameScore = 15;
    } else {
      fraudFlags.push("ACCOUNT_NAME_MISMATCH");
    }

    // 4. Date Match (10 points)
    // Transaction date must be on or after invoice creation date
    const invoiceCreatedDate = new Date(invoice.createdAt);
    invoiceCreatedDate.setHours(0, 0, 0, 0);
    const receiptDate = ocr.transaction_date ? new Date(ocr.transaction_date) : new Date();
    receiptDate.setHours(0, 0, 0, 0);
    
    if (receiptDate >= invoiceCreatedDate) {
      dateScore = 10;
    } else {
      fraudFlags.push("INVALID_TRANSACTION_DATE");
    }

    // 5. Reference Match (10 points)
    // Extracted transaction reference matches submitted reference or invoice number
    const extRefUpper = ocr.transaction_reference.toUpperCase().trim();
    const subRefUpper = submittedRef.toUpperCase().trim();
    if (subRefUpper && (extRefUpper === subRefUpper || extRefUpper.includes(subRefUpper) || subRefUpper.includes(extRefUpper))) {
      referenceScore = 10;
    } else {
      fraudFlags.push("REFERENCE_MISMATCH");
    }

    // Calculate preliminary total score
    let totalScore = amountScore + accountNumberScore + accountNameScore + dateScore + referenceScore;

    // Fraud Flag Deductions & Cap Checks
    let isSuspectedFraud = ocr.suspected_fraud;
    if (isSuspectedFraud) {
      ocr.fraud_reasons.forEach(r => fraudFlags.push(r.toUpperCase().replace(/\s+/g, "_")));
      // Force manual review/rejection if Gemini flags suspected fraud
      totalScore = Math.min(totalScore, 50);
    }

    // Low confidence caps the score to force manual review
    if (ocr.confidence_score < 70) {
      fraudFlags.push("LOW_GEMINI_CONFIDENCE");
      totalScore = Math.min(totalScore, 59); // Forces REJECTED or MANUAL_REVIEW depending on other fields
    }

    // Determine status
    let status: VerificationScore["status"] = "REJECTED";
    if (totalScore >= 90 && !isSuspectedFraud && ocr.confidence_score >= 80) {
      status = "AUTO_VERIFIED";
    } else if (totalScore >= 60) {
      status = "MANUAL_REVIEW";
    }

    return {
      amountScore,
      accountNumberScore,
      accountNameScore,
      dateScore,
      referenceScore,
      totalScore,
      status,
      fraudFlags,
      isSuspectedFraud
    };
  }

  /**
   * Execute full verification flow including duplicate/reused receipt checks, file size verification, and DB insertion.
   */
  static async verifyReceipt(
    invoiceId: string,
    file: File,
    submittedRef: string,
    ipAddress?: string,
    userAgent?: string
  ): Promise<{ success: boolean; attemptId: string; score: VerificationScore; extracted: GeminiOcrResult }> {
    // 1. File Size Verification (Max 5MB)
    const MAX_FILE_SIZE = 5 * 1024 * 1024;
    if (file.size > MAX_FILE_SIZE) {
      throw new Error("Receipt file size exceeds the 5MB limit.");
    }

    // Fetch Invoice
    const invoice = await db.query.invoices.findFirst({
      where: eq(invoices.id, invoiceId),
    });

    if (!invoice) {
      throw new Error("Invoice not found.");
    }

    // Convert to Base64
    const buffer = Buffer.from(await file.arrayBuffer());
    const base64Data = buffer.toString("base64");
    const mimeType = file.type;

    // Generate SHA-256 Image Hash for duplicate check
    const imageHash = createHash("sha256").update(base64Data).digest("hex");

    // 2. Extract Details with Gemini Vision
    const ocrResult = await this.extractReceiptDetails(base64Data, mimeType);

    // 3. Duplicate checks
    let duplicateDetected = false;
    let reuseRefDetected = false;

    // Check if the exact image hash was uploaded before
    const existingUpload = await db.query.receiptUploads.findFirst({
      where: eq(receiptUploads.receiptImageBase64, base64Data),
    });
    if (existingUpload) {
      duplicateDetected = true;
    }

    // Check if transaction reference was used on another verified/paid invoice
    if (ocrResult.transaction_reference && ocrResult.transaction_reference !== "N/A") {
      const duplicateRefAttempt = await db.query.verificationAttempts.findFirst({
        where: and(
          eq(verificationAttempts.extractedRef, ocrResult.transaction_reference),
          eq(verificationAttempts.status, "AUTO_VERIFIED")
        )
      });
      if (duplicateRefAttempt) {
        reuseRefDetected = true;
      }
    }

    // 4. Run Scorer
    const score = await this.scoreReceipt(ocrResult, invoice, submittedRef);

    // Overlay duplicate findings
    if (duplicateDetected) {
      score.fraudFlags.push("DUPLICATE_RECEIPT_IMAGE");
      score.isSuspectedFraud = true;
      score.totalScore = Math.min(score.totalScore, 30);
      score.status = "REJECTED";
    }
    if (reuseRefDetected) {
      score.fraudFlags.push("REUSED_TRANSACTION_REF");
      score.isSuspectedFraud = true;
      score.totalScore = Math.min(score.totalScore, 40);
      score.status = "REJECTED";
    }

    // 5. Insert Receipt Upload Record
    const [upload] = await db.insert(receiptUploads).values({
      invoiceId,
      fileName: file.name,
      fileSize: file.size,
      fileType: file.type,
      receiptImageBase64: base64Data,
    }).returning();

    // 6. Insert Verification Attempt
    const [attempt] = await db.insert(verificationAttempts).values({
      invoiceId,
      receiptUploadId: upload.id,
      confidenceScore: ocrResult.confidence_score,
      extractedAmount: ocrResult.amount,
      extractedAccountNumber: ocrResult.account_number,
      extractedAccountName: ocrResult.account_name,
      extractedBankName: ocrResult.bank_name,
      extractedRef: ocrResult.transaction_reference,
      extractedSenderName: ocrResult.sender_name,
      extractedDate: ocrResult.transaction_date,
      scoreAmount: score.amountScore,
      scoreAccountNumber: score.accountNumberScore,
      scoreAccountName: score.accountNameScore,
      scoreDate: score.dateScore,
      scoreReference: score.referenceScore,
      totalScore: score.totalScore,
      status: score.status,
      fraudFlags: score.fraudFlags,
      isSuspectedFraud: score.isSuspectedFraud,
      ocrRawResult: ocrResult,
    }).returning();

    // 7. Write Audit Log
    await db.insert(auditLogs).values({
      userId: invoice.userId,
      eventType: `RECEIPT_VERIFICATION_${score.status}`,
      entityType: "invoice",
      entityId: invoiceId,
      changes: {
        score: score.totalScore,
        status: score.status,
        flags: score.fraudFlags,
        extractedReference: ocrResult.transaction_reference,
      },
      ipAddress: ipAddress || "127.0.0.1",
      userAgent: userAgent || "Kavio Scorer",
      metadata: {
        attemptId: attempt.id,
        invoiceNumber: invoice.invoiceNumber,
      }
    });

    // 8. Update Invoice Status to VERIFIED or UNDER_REVIEW (NEVER mark PAID automatically!)
    const updatedStatus = score.status === "AUTO_VERIFIED" ? "VERIFIED" : "UNDER_REVIEW";
    await db.update(invoices)
      .set({ status: updatedStatus, updatedAt: new Date() })
      .where(eq(invoices.id, invoiceId));

    // Fetch freelancer details for email templates
    const freelancer = await db.query.users.findFirst({
      where: eq(invoices.userId, invoice.userId),
    });

    const client = await db.query.clients.findFirst({
      where: eq(invoices.clientId, invoice.clientId),
    });

    if (freelancer && client) {
      const emailInvoice = {
        id: invoice.id,
        invoiceNumber: invoice.invoiceNumber,
        amount: invoice.amount,
        clientName: client.name,
        freelancerName: freelancer.name || "Freelancer",
        freelancerEmail: freelancer.email,
        clientEmail: client.email,
      };

      // 9. Send general Notification
      await db.insert(notifications).values({
        userId: invoice.userId,
        title: score.status === "AUTO_VERIFIED" ? "Invoice Payment Verified" : "Payment Awaiting Review",
        message: score.status === "AUTO_VERIFIED" 
          ? `Gemini verified payment of ₦${ocrResult.amount.toLocaleString()} for Invoice ${invoice.invoiceNumber}.`
          : `Receipt uploaded for Invoice ${invoice.invoiceNumber} requires manual verification.`,
        type: score.status === "AUTO_VERIFIED" ? "invoice_verified" : "manual_review_required",
      });

      // 10. Send Resend Emails in the background
      if (score.status === "AUTO_VERIFIED") {
        await NotificationService.sendInvoiceVerified({
          invoice: emailInvoice,
          trustScore: score.totalScore,
        }).catch(e => console.error("Email send failed", e));
      } else if (score.status === "MANUAL_REVIEW") {
        await NotificationService.sendManualReviewRequired({
          invoice: emailInvoice,
          trustScore: score.totalScore,
          reason: score.fraudFlags.join(", ") || "Details match partially, requires freelancer clearance.",
        }).catch(e => console.error("Email send failed", e));
      }

      // Send a general notification that receipt was uploaded
      await NotificationService.sendReceiptUploaded({
        invoice: emailInvoice,
        uploadDetails: {
          fileName: file.name,
          fileSizeKB: Math.round(file.size / 1024),
          totalScore: score.totalScore
        }
      }).catch(e => console.error("Email send failed", e));
    }

    return {
      success: score.status !== "REJECTED",
      attemptId: attempt.id,
      score,
      extracted: ocrResult,
    };
  }

  // --- PRIVATE UTILITIES ---

  private static getMockOcrResult(): GeminiOcrResult & { suspected_fraud: boolean; fraud_reasons: string[] } {
    return {
      amount: 150000,
      account_number: "0123456789",
      account_name: "Mock Freelancer Ltd",
      bank_name: "OPay",
      transaction_reference: `REF-${Math.floor(100000 + Math.random() * 900000)}`,
      sender_name: "Mock Client",
      transaction_date: new Date().toISOString().split("T")[0],
      confidence_score: 95,
      suspected_fraud: false,
      fraud_reasons: []
    };
  }

  private static computeJaroWinkler(s1: string, s2: string): number {
    let m = 0;
    if (s1.length === 0 || s2.length === 0) return 0;
    if (s1 === s2) return 1;

    const range = Math.floor(Math.max(s1.length, s2.length) / 2) - 1;
    const s1Matches = new Array(s1.length);
    const s2Matches = new Array(s2.length);

    for (let i = 0; i < s1.length; i++) {
      const low = Math.max(0, i - range);
      const high = Math.min(s2.length - 1, i + range);
      for (let j = low; j <= high; j++) {
        if (!s1Matches[i] && !s2Matches[j] && s1[i] === s2[j]) {
          s1Matches[i] = true;
          s2Matches[j] = true;
          m++;
          break;
        }
      }
    }

    if (m === 0) return 0;

    let t = 0;
    let k = 0;
    for (let i = 0; i < s1.length; i++) {
      if (s1Matches[i]) {
        while (!s2Matches[k]) k++;
        if (s1[i] !== s2[k]) t++;
        k++;
      }
    }

    const jaro = (m / s1.length + m / s2.length + (m - t / 2) / m) / 3;
    return jaro;
  }
}
